nested_brackets.go

As requested in #4 I added the algorithm to the nested brackets problem.

Add nested brackets algorithm

---

sorts/TopologicalSort.go

https://github.com/TheAlgorithms/Go/issues/4

adds topological sort

---

Linkedlist.go

I added linkedlist with these methods: pushback, pushfront, popback and popfront.

Added linkedlist

---

sorts/Radix.go

If there are coding styles or tests that I should write, please let me know

Added Radix Sort to sorts

---

data-structures/binary-tree/binary-search-tree.go
data-structures/binary-tree/binary-tree.go

Following functionalities have been implemented
Supports #4

Add binary tree and binary search tree

---

sorts/insertion_sort.go

Replace `sortedvals:= range` with `_, sortedvals := range arr` and reformat code.

fix insertion sort error and reformat file

---

strings/naiveStringSearch.go

Created strings folder and added naive pattern search. Please review. :)

created strings folder and added naiveStringSearch

---

other/maxSubarraySum.go

Added maxSubarraySum in 'other' directory. Please review it :)

O(n) solution for maximum contiguos subarray sum

---

other/maxSubarraySum.go

Uses range to loop over the array enchancing code readibility

Simplify the array looping

---

strings/multiple string matching/ac.go
strings/multiple string matching/adac.go
strings/multiple string matching/patterns.txt
strings/multiple string matching/sbom.go
strings/multiple string matching/text.txt
strings/naiveStringSearch.go
strings/single string matching/bom.go
strings/single string matching/horspool.go
strings/single string matching/kmp.go
strings/single string matching/pattern.txt
strings/single string matching/text.txt

Previously naive pattern search did not run
Closes #134

fix naive pattern searching + add more string matching algorithms

---

dynamic-programming/longestCommonSubsequence.go

I have implemented the "Longest Common Subsequence" using Dynamic Programming in Go.

Implemented Longest Common Subsequence in GoLang

---

sorts/bubble_sort.go

Go go swap array variable quickly, no need to implement a swap function.

update bubblesort swap

---

DIRECTORY.md
ciphers/RSAcipher(Big).go

The code is more practical generates 1024 bit keys, unlike my previous implementation which took forever with just a 20 bit key

Implemented RSA using math\big library

---

.github/workflows/golangci-lint.yml

Revert "golangci-lint.yml: Upgrade go and Actions"

---

.github/workflows/golangci-lint.yml

Can anyone provide pointers on getting this GitHub Action to work?  I can not quite decipher the output of trying to get `golangci/golangci-lint-action` working.  I know that lint will fail but I had hoped that `args: --issues-exit-code=0` would show us where the errors are.

Re-recreate #146

---

searches/search_test.go

add search tests

---

searches/breadth_first_search.go
searches/depth_first_search.go

Hi
I implemented depth first search, breadth first search algorith.

implemented dfs, bfs

---

DIRECTORY.md
graphs/floyd_warshall.go

Added implementation of Floyd-Warshall algorithm and added it's link in DIRECTORY.md
#4

Added implementation of Floyd-Warshall algorithm

---

sorts/counting_sort.go

Hello,  I just added counting sort and  I want to contribute to the development of this  repository, thank you.

added counting sort

---

other/monte_carlo_pi/monte_carlo_pi.go
other/monte_carlo_pi/monte_carlo_pi_test.go

Add Monte Carlo Pi algorithm as asked in #4

add Monte Carlo Pi algorithm

---

ciphers/RSAcipher.go
ciphers/diffieHellmanKeyExchange.go
ciphers/xorCipher.go
math/fastExponent.go
other/NestedBrackets.go
searches/binary_search.go
sorts/sorts_case_test.go
strings/naiveStringSearch.go

Code refactoring

---

strings/levenshteinDistance.go

This PR includes a new algorithm to calculate distance between two strings using Levenshtein Distance (Wagner-Fischer algorithm).
The algorithm uses different weights for insertions, deletions and substitutions.

Levenshtein distance

---

sorts/bubble_sort.go

Add more information to bubble_sort.go.

Refactor bubble_sort.go

---

data-structures/hash-map/hash_map.go
data-structures/hash-map/hash_map_test.go
go.mod

- Made Hashmap exportable 
- move commented code in a test file
- added go modules support
I'm also planning to add more tests to check hashmap functionality

Refactored hashmap 

---

.github/PULL_REQUEST_TEMPLATE/pull_request.md

Signed-off-by: Jobin John <jobin1094@gmail.com>
Added a basic PR template md file. Reasons:
- Observed that many contributors were creating PRs with blank or insufficient description on what has been added/removed and why. 
- There is also a tendency to open PRs that do not have an issue associated to it.
This is an effort made to set some guidelines that will help both the contributors and maintainers.

Add a basic pull request template.

---

.github/workflows/golangci-lint.yml
strings/levenshteindistance/levenshteinDistance.go
strings/levenshteindistance/levenshteinDistance_test.go
strings/naivesearch/naiveStringSearch.go
strings/naivesearch/naiveStringSearch_test.go

Changes made:
1. Levenshtein Distance algorithm
- Moved files into appropriate folder and renamed package to fix ci lint error.
- Removed unnecessary slice added for swap.
- Removed main func. Added test file instead.
- Removed an unused func: "min". 
2. Naive Search algorithm
- Moved files into appropriate folder and renamed package to fix ci lint error.
- Removed main func. Added test file instead.
- Fixed a logic error where the possibility of pattern being found at the end of the string wasn't considered.
Fixes part of #145

Add tests for Levenshtein distance and naive search algorithms

---

ciphers/rot13/rot13.go
ciphers/rot13/rot13_test.go

Hi, continuing my work on issue #145 and using the structure used in PR #197. With this PR i'm adding some tests for the rot13 algorithm. As in my recent PRs the tests work on the created package but not when running them on the whole project.

tests for rot13 algorithm

---

math/pythagoras/pythagoras.go
math/pythagoras/pythagoras_test.go

Calculates the distance between to vectors/points in space with the Pythagoras Theorem.

Added Pythagoras Theorem

---

searches/binary_search.go
searches/search_test.go

Reverts TheAlgorithms/Go#245
Some more modifications to be added to handle edge cases.

Revert "Update iterBinarySearch"

---

dynamicprogramming/fibonacc_test.go
dynamicprogramming/fibonacci.go

Fixes https://github.com/TheAlgorithms/Go/issues/228
Add the basic dynamic programming algorithm for calculating Nth Fibonacci number from https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/

Add fibonacci algorithm by dynamic programming

---

ciphers/xor/xorCipher.go
ciphers/xor/xor_cipher_test.go

- refactor the codes in xor package
- remove redundant codes
- e.g.) [func xor](https://github.com/TheAlgorithms/Go/blob/master/ciphers/xor/xorCipher.go#L11-L13)
- update the type of arguments
- for improving flexibility for using various types
- add example test

Refactor xor package

---

ciphers/polybius/polybius_test.go

My bad. I missed the typo in test for Polybius package.
- Fix misspelling in test for polybius package
refers: #259

Fix typo in polybius package

---

ciphers/rot13/rot13.go
go.mod
go.sum

This is a simple fix to the issue #271 
I've also cleared the dependency graph of this repo so I don't expect to see any issues.

Fix: Tests work on the TheAlgorithms/Go repository 

---

CONTRIBUTING.md
DIRECTORY.md
data_structures/dynamic_array/dynamic_array.go
data_structures/dynamic_array/dynamic_array_test.go

Fix: In #273547e changed the file name from pull_request.go to pull_request.md .
Test: In #46e0651  added a test for dynamic array (filename : dynamic_array_test.go)
Docs: In #46e0651 added comments based on guidelines to more clear it   (filename : dynamic_array.go)
Other commits were #5963c30, #5963c30, and #07d700d. I just fixed my English grammar and the path of dynamic_array in the Directory.md file.

fixed CONTRIBUTING.md and added testcase to dynamic array

---

searches/interpolation_search.go/interpolation_search_test.go
searches/interpolation_search.go/interpolationsearch.go

Interpolation Search 

---

README.md

Fix links - connected to issue #344

doc: fix: Fix links in README.md

---

CONTRIBUTING.md
README.md
graph/coloring/backtracking.go
graph/coloring/backtracking_test.go
graph/coloring/bfs.go
graph/coloring/bfs_test.go
graph/coloring/doc.go
graph/coloring/graph.go
graph/coloring/graph_test.go
graph/coloring/greedy.go
graph/coloring/greedy_test.go
graph/doc.go
graph/graph.go

This will add 3 graph coloring algorithms
* Using BFS
* Using Backtracking
* Using Greedy Approach
Ref #33

feat: add Graph Coloring algorithms

---

conversion/integertoroman.go
conversion/integertoroman_test.go
conversion/romantointeger.go
conversion/romantointeger_test.go

- Added an algorithm for converting an integer to a roman numeral string
- Optimized the existing roman numeral string to integer algorithm. I also made it to return an error if out of bounds, not sure if this is allowed as the old algorithm did not return an error. let me know if that part should be removed
Benchmarks:

optimized roman to int and added int to roman

---

README.md
conversion/romantointeger.go

- Added new link
- Using "Roman Numeral" instead of just "Roman" for clarity

Updated README to include new int to roman function

---

structure/binarytree/btree_test.go

Hi, I added a test file for some functions in binary tree.  I can't write test for traversal (in-order, pre-order, post-order, level order) because it is not testable (at least that's what I thought). I can update the function and write the test if you want me to do.  If not please consider to review this one. Thank you!

add btree test file

---

structure/binarytree/btree.go
structure/binarytree/btree_test.go

Hi, I changed the binary tree traversal implementation so it return the traversal instead of print it. I also added the test. Please consider to review this change. Thank you.

Change binary tree traversal implementation and add the test

---

strings/generateparentheses/generateparentheses.go
strings/generateparentheses/generateparentheses_test.go

Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

feat: generate parentheses

---

search/binary_test.go
search/interpolation.go
search/interpolation_test.go
search/linear.go
search/linear_test.go
search/testcases.go

I have added error value to Linear search and Interpolation search. I have also added benchmark so the efficiency of searches can be compared.

Add error value to search and add related benchmark

---

dynamic/editdistance.go
dynamic/editdistance_test.go

Hi guys! I saw that the algorithm for this was missing from the collection of dynamic programming algorithms. So I went ahead and wrote this.

Edit Distance Problem

---

CONTRIBUTING.md

Add a section about preparation for pull request in order to fix #359 .

Adjust instructions in CONTRIBUTING.md

---

.github/workflows/godocmd.yml

Fix for action - forgot to checkout the repo in a non-detached state.

fix: godocmd

---

README.md
strings/pangram/ispangram.go
strings/pangram/ispangram_test.go

Add Pangram program

---

README.md
math/armstrong/isarmstrong.go
math/armstrong/isarmstrong_test.go

Adding program to check if the number is an Armstrong number

---

search/jump2.go
search/jump2_test.go

feat: add a clear implemention of jump search

feat: add a clear implemention of jump search

---

search/selectk.go
search/selectk_test.go

* feat: add qucik select algorithm

feat: add qucik select algorithm

---

.github/workflows/ci.yml
.github/workflows/godocmd.yml
.github/workflows/golang_lint_and_test.yml

Update repository workflows

---

CONTRIBUTING.md
graph/dijkstra.go
sort/heapsort.go
structure/dynamicarray/dynamicarray.go
structure/dynamicarray/dynamicarray_test.go
structure/hashmap/hashmap.go
structure/hashmap/hashmap_test.go
structure/linkedlist/cyclic.go
structure/linkedlist/cyclic_test.go
structure/linkedlist/doubly.go
structure/linkedlist/shared.go
structure/linkedlist/singlylinkedlist.go
structure/linkedlist/singlylinkedlist_test.go
structure/queue/queue_test.go
structure/queue/queuearray.go
structure/queue/queuelinkedlist.go
structure/queue/queuelinklistwithlist.go
structure/set/set.go
structure/stack/stack_test.go
structure/stack/stackarray.go
structure/stack/stacklinkedlist.go
structure/stack/stacklinkedlistwithlist.go

replaced 'interface{}' with 'any' using new go1.18 alias

---

cipher/diffiehellman/diffiehellmankeyexchange.go

There was a slight error in the name of the algorithm in the comments.

Fixed typo in name of algorithm.

---

sort/patiencesort.go
sort/sorts_test.go

feat: add patience sorting algorithm
test: add test for patience sorting algorithm

add patience sorting algorithm

---

structure/linkedlist/Readme.md

Have added a useful resource about the linked list in a data structure from the scaler topics.

doc: Added a useful resource

---

README.md
other/password/generator.go
structure/linkedlist/doc.go
structure/trie/trie_bench_test.go

Fixing some spellcheck issues that are happening across repo and breaking CI

fix: spellcheck

---

structure/linkedlist/cyclic.go
structure/linkedlist/cyclic_test.go
structure/linkedlist/doubly.go
structure/linkedlist/doubly_test.go
structure/linkedlist/shared.go
structure/linkedlist/singlylinkedlist.go
structure/linkedlist/singlylinkedlist_test.go

Added generic syntax for /structure/linkedlist; led to also having a need to change
some function signatures e.g
func (ll *Singly[T]) DelAtBeg() int // -1 on not-found
->
func (ll *Singly[T]) DelAtBeg() (T, bool)

add generics

---

math/binomialcoefficient.go
math/binomialcoefficient_test.go

algorithm: binomial coefficient

---

math/lerp.go
math/lerp_test.go

Add function lerp for calculating liner interpolation
this function will return a value between input v0, and v1 with t%

feat: add lerp

---

dynamic/longestcommonsubsequence_test.go

I added tests for [`longestcommonsubsequence.go`](https://github.com/TheAlgorithms/Go/blob/51f0485f9289676e23d4c7cbf4a868e4704a27d6/dynamic/longestcommonsubsequence.go). There are two new tests: the first one checks is a basic check of the result of the function `LongestCommonSubsequence`. The second one checks if the function `LongestCommonSubsequence` is _symmetric_.
The example data was verified using:
- https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/
- https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/longest_common_subsequence.py
Notes: 
Added tests for [`longestcommonsubsequence.go`](https://github.com/TheAlgorithms/Go/blob/51f0485f9289676e23d4c7cbf4a868e4704a27d6/dynamic/longestcommonsubsequence.go).

test: add tests for longestcommonsubsequence.go

---

dynamic/rodcutting_test.go

I have added tests for [`rodcutting.go`](https://github.com/TheAlgorithms/Go/blob/51f0485f9289676e23d4c7cbf4a868e4704a27d6/dynamic/rodcutting.go). The test data is verified using
- https://sites.radford.edu/~nokie/classes/360/dp-rod-cutting.html
- https://www.geeksforgeeks.org/cutting-a-rod-dp-13/
Tests check both existing implementations of the solution.
Notes: 
Added tests for [`rodcutting.go`](https://github.com/TheAlgorithms/Go/blob/51f0485f9289676e23d4c7cbf4a868e4704a27d6/dynamic/rodcutting.go).

test: add tests for rodcutting.go

---

math/perfectnumber.go
math/perfectnumber_test.go

I have added an utility allowing to check if given number is [_perfect_](https://en.wikipedia.org/wiki/Perfect_number).
The check is done by comparing the sum of the [proper divisors](https://mathworld.wolfram.com/ProperDivisor.html) with the input.
The proper divisors are obtained by iterating though all of the natural numbers up to the square root of the input. 
Notes: 
Added [`perfectnumber.go`](https://github.com/vil02/Go/blob/ff1a8f074977ecb94ae402f1aa6e7d9b360abcf6/math/perfectnumber.go) and respective [tests](https://github.com/vil02/Go/blob/ff1a8f074977ecb94ae402f1aa6e7d9b360abcf6/math/perfectnumber_test.go).

feat: add perfectnumber

---

sort/mergesort.go
sort/sorts_test.go

Related issue:  #552 
I've added the Parallel MergeSort algorithm using goroutines and the corresponding tests.

feat: Parallel MergeSort using goroutines

---

math/modular/inverse.go
math/modular/inverse_test.go

I added test cases checking the output of `Inverse(2, 6)` and `Inverse(1, 0)`. I adapted the function `Inverse` to return an `ErrorInverse` if its second argument is zero. The remaining changes are some minor _code clean-ups_.
Notes: 
Added test cases for the function `Inverse` covering the _unhappy path_.

tests: Modular Inverse

---

CONTRIBUTING.md

Bolded "removing bugs" on line 28.

fix: README

---

math/aliquot_test.go
math/aliquotsum.go

This PR contains implementation for Aliquot Sum. Kindly have a look.
Thanks.

algorithm: Aliquot Sum

---

strings/guid/guid.go
strings/guid/guid_test.go

Algorithm implementation for GUID strings generation.
Generation occurs for the following pattern `xxxxxxxxxx-xxxxxxx-4xxxxx-xxxxxxx-xxxxxxxxx`, where a random hexadecimal value (from 0 to f) is substituted for the `x` values. The robust `rand` function from the `crypto` package was used to get the random values.
Read more about GUID: https://en.wikipedia.org/wiki/Universally_unique_identifier
Other implementation from TheAlgorithms website: https://the-algorithms.com/search?q=GUID

feat: add GUID algorithm

---

math/krishnamurthy.go
math/krishnamurthy_test.go

Added the Krishnamurthy Algorithm implementation along with the tests and benchmarks for the code. Please review the pull request.

Adding Krishnamurthy number algorithm

---

.gitpod.dockerfile
.gitpod.yml

This PR adds a basic gitpod configuration - the _automatically generated_ `.gitpod.yml` does not work with this project. Similar to TheAlgorithms/Java#4243.
Notes: 
Adds basic gitpod configuration.

chore: add basic gitpod configuration

---

.github/workflows/ci.yml
.github/workflows/godocmd.yml

The `actions/checkout@v4` was recently [released](https://github.com/actions/checkout/releases/tag/v4.0.0). This PR makes a suitable update.
Notes: 
Update `actions/checkout` to `v4`.

chore: update `actions/checkout` to `v4`

---

strings/parenthesis/parenthesis.go

Removed line breaks and made small changes to the comments.

refactored comments to comply with godocs

---

README.md
sort/bogosort.go
sort/sorts_test.go

add bogo sort

---

.github/workflows/citk.yml

In this PR, we use the `citk` tool that I have been building over the past few days. This is something @Panquesito7 and I wanted to do for quite a while but didn't get around to it.
The tool is quite simple actually but for us to test it in a big codebase, I used this repository as a target for the Go POC.
There is a test PR on this repo, where you can find the annotation. [Here's the diff](https://github.com/TheAlgorithms/Go/pull/640/files#diff-2146d0fbe654d74be70917b88eba22fd73544e48377b4552bef07c2ba7a61ac4) where the annotation is presented. Let me know what you guys think. 
Another thing to note is that I'm not failing the CI job when the annotations do occur, I think I should but I wanted to ask others, so let me know if I should.

Using citk for Go repo

---

strings/issubsequence.go
strings/issubsequence_test.go

Add isSubsequence string algorithm

Add isSubsequence string algorithm

---

graph/cycle.go
graph/cycle_test.go

i added cycle detection in graph package and other function that list all detected cycles in graph also added tests and docs
Notes:

feat: graph cycle detection

---

README.md
cache/lfu.go
cache/lfu_test.go
cache/lru.go

Description of Change
This PR adds LFU cache algorithm implementation.
Checklist
Notes: This PR contributes a Timsort sorting algorithm implementation and includes it to the test file.

feat:add lfu cache alogrithm

---

strings/parenthesis/parenthesis_test.go

fixed typos

---

LICENSE

I hope that ```Copyright (c) 2021 The Algorithms and contributors``` will make your project more open and clear to understand what is going on inside this project.
Thanks for your contribution, happy hacking ! and happy new year !

Copyright Holders Update to make it more clear

---

.github/CODEOWNERS

I'm removing myself (`tjgurwara99`) from the code owners here.

Remove a codeowner who is not active on the repository anymore

---

math/catalan/catalannumber.go
math/factorial/factorial.go
math/factorial/factorial_test.go

Current implementations of the factorial react differently for negative inputs. This PR fixes that. Furthermore it reduced the code duplication in the corresponding test file by expressing tests and benchmarks as _parameterized_.

style: handle edge cases uniformly in all implementations of factorial

---

graph/bellmanford.go

I was investigating algms implementations in repo and saw a typo and decided to open a PR just to keep this repo prettier than it is.

fix: typo in bellmanford description
