data-structures/linked-list/double-linkedlist.go
data-structures/linked-list/single-linkedlist.go

Implemented **single** and **double linked lists** with following operations
Supports #4

implement linkedlists

---

searches/binary_search.go

Adding two large integers then dividing the sum, (a+b)/2 ,might end up creating a sum that can't fit in memory. However this overflow can be avoided by never adding the numbers first instead, adding the difference of the two numbers to the least i.e (a+b)/2 == a+(b-a)/2 == b-(b-a)/2 ... Please comment or ask for further clarification instead of just rejecting the proposal. Thanks

Avoids Overflow Errors common in Binary search

---

data-structures/binary-tree/binary-search-tree.go

Old
t := &btree{nil}
// inorder(t.root)
t.root = insert(t.root, 30)
t.root = insert(t.root, 20)
t.root = insert(t.root, 15)
t.root = insert(t.root, 10)
t.root = insert(t.root, 12)
t.root = insert(t.root, 8)
t.root = insert(t.root, 6)
t.root = insert(t.root, 4)
t.root = bst_delete(t.root, 10)
inorder(t.root)  // 4 6 8 4 12 15 20 30
Now
t := &btree{nil}
// inorder(t.root)
t.root = insert(t.root, 30)
t.root = insert(t.root, 20)
t.root = insert(t.root, 15)
t.root = insert(t.root, 10)
t.root = insert(t.root, 12)
t.root = insert(t.root, 8)
t.root = insert(t.root, 6)
t.root = insert(t.root, 4)
t.root = bst_delete(t.root, 10)
inorder(t.root)  // 4 6 8  12 15 20 30

BinarySearchTree delete wrong

---

searches/binarysearch.go
searches/search_test.go

For recursive binary search code, there was a stack overflow problem when the target value is less than smallest value in the array, and the iterate version code also failed in many test cases, i fix the bug and add more test for current binary search code. 
Test result : 
```
=== RUN   TestBinarySearch
--- PASS: TestBinarySearch (0.00s)
=== RUN   TestIterBinarySearch
--- PASS: TestIterBinarySearch (0.00s)
=== RUN   TestLinearSearch
--- PASS: TestLinearSearch (0.00s)
PASS
```

fix stack overflow problem and add more test

---

ciphers/caesar/CaesarCipher.go
ciphers/caesar/caesar_test.go

- add lacked processings
- adapts not only lowercase but also uppercase
- implements decrypt function
- fix typo
- package name
- some words in test
- add lacked test cases
- coverage(64.7%=>100.0%) 
refers: #13 #197 #260

Add lacked tests for caesar cipher

---

ciphers/rot13/rot13.go

I've changed from original implementation to the way using tested "caesar" package because rot13 is a special case, which is fixed the shift of 13, of the Caesar cipher. 
ref: https://en.wikipedia.org/wiki/ROT13
Package rot13 has error below on testing.
```
$ go test -v -parallel=4 -covermode=atomic ./ciphers/rot13/...
ciphers/rot13/rot13.go:23: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL    TheAlgorithms/Go/ciphers/rot13 [build failed]
FAIL
```
Containing this package into "caesar" package is also one of the way to fix this error. If this way is preferable, I will fix this pull request.

fix rot13 content

---

other/nested_brackets/nestedbrackets.go
other/nested_brackets/nestedbrackets_test.go

Couple issues of `IsBalanced` function of the `nested_brackets` has been fixed as well as documentation was added for the package and a function:
- Changed return type of the function from `void` to `bool` as it was initially suggested by documentation (this made function testable);
- Improved performance by replacing length check of input string with special case check in the beginning of the function;
- added suitable description of the package;
- added description for `IsBalanced` function (previous description was used as the base);
- added tests for the `IsBalanced` function, all special cases included;
- added benchmark for `IsBalanced` function;
<br>
<br>
Original algorithm implementation logic is preserved for 100%. Minor changes are made to function body in order to make code …

fix, docs, test: nested brackets algorithm.

---

genetic_algorithm/geneticalgorithm.go
genetic_algorithm/geneticalgorithm_test.go

Package `genetic_algorithm/geneticalgorithm` contains single function called `GeneticString`. Couple changes has been made to the code of the function related to providing configuration to function and retrieving result of the function execution.
Previously, function used to return tuple which contains result of generation as well as some details about generation process. Output was changed to the single go struct and an error, in order to make function testable (in case of errors).
In comparison with the previous output, when only a resulting string was provided, new output also contains a value, used inside the process, what can be useful for later function extensions.
Configuration previously hardcoded, now can be provided withing configuration structure. This feature can be used to …

docs, test: genetic algorithm

---

hashing/doc.go
hashing/hashing_test.go
hashing/sha256/sha256.go
hashing/sha256/sha256_test.go

An implementation of the sha256 cryptographic hash function as defined in the [RFC6234](https://datatracker.ietf.org/doc/html/rfc6234) standard. The Wikipedia page: https://en.wikipedia.org/wiki/SHA-2
---
I am not sure which folder to put the implementation in, but I tried to match the consensus on [The Algorithms](https://the-algorithms.com/search?q=sha256) website, which seems to put it in the "hashing" category.
Let me know what you think!

feat: add hashing/sha256 implementation

---

.github/workflows/godocmd.yml

As the title suggests, currently some actions were failing and the issue is because the checkout was happening in detached state. The fetch-depth 0 fixes that and the only problem afterwards is that the master is protected (as it should be) so on pull_requests the action would always fail. Therefore, I moved it to push only so that when the push occurs in forks it should run to create the documentation. Sorry about the multiple PRs, my local rebase became messy and tbh both cherry picking rebasing is difficult for me.

fix: only to run when push happens - upstream master is protected but not the forks master

---

math/pi/montecarlopi.go
math/pi/montecarlopi_test.go

Hi everyone!
I suggest a second implementation, inspired by @i-redbyte's implementation of a Monte Carlo method for pi approximation in Go. This new implementation builds on the first one, but makes use of the goroutines and channels features of Go, in order to parallelize the computation.
The speed is the largely increased, allowing full use of the computer's multiprocessing capabilities.
---
Here are the benchmarks ran on my machine:
```
goos: windows
goarch: amd64
pkg: github.com/TheAlgorithms/Go/math/pi
cpu: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
BenchmarkMonteCarloPi
BenchmarkMonteCarloPi-6   	       2	 613621650 ns/op
```
```
goos: windows
goarch: amd64
pkg: github.com/TheAlgorithms/Go/math/pi
cpu: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
BenchmarkMonteCarloPi2 …
```

feat: add math/MontecarloPi2 implementation

---

graph/breadthfirstsearch.go

Remove redundant if clause which condition is always met at line of execution
The condition of the for loop and the if clause are identical, so the condition of the if clause will always be met
I would suggest refactoring line 15,16 to
`v, queue := queue[0], queue[1:]` 
as well, but perhaps it is better to keep it simpler.

Simplify BreadthFirstSearch.go

---

.github/workflows/godocmd.yml
.github/workflows/golang_lint_and_test.yml
README.md
constraints/contraints.go
go.mod
sort/bubblesort.go
sort/combSort.go
sort/countingsort.go
sort/exchangesort.go
sort/insertionsort.go
sort/mergesort.go
sort/quicksort.go
sort/selectionsort.go
sort/shellsort.go
sort/simplesort.go
sort/sorts_test.go

Beginning of Generics in Go. A relatively simple PR to include some examples use cases of Generics in sort. Was not able to actually convert some of the sort algorithms due to their intrinsic dependence on type `int`.

fix: [generic + sort] All ready for generics

---

conversion/base64_test.go

As discussed in #480 , with the new Go version (1.18), we can now start adding Fuzzing tests to some of our algorithms.
This is my first try at this feature, so I would like your opinion on the code, and wheen it'll look good to you, I can work on implementing fuzzing tests on other algorithms.
To run this fuzzing test:
```
cd conversion
go test -fuzz FuzzBase64Encode
```
It'll run indefinitely by default, you can stop it with ctrl+c.
Example output:
```
fuzz: elapsed: 0s, gathering baseline coverage: 0/15 completed
fuzz: elapsed: 0s, gathering baseline coverage: 15/15 completed, now fuzzing with 12 workers
fuzz: elapsed: 3s, execs: 445059 (148282/sec), new interesting: 0 (total: 14)
fuzz: elapsed: 6s, execs: 946614 (167085/sec), new interesting: 0 (total: 14)
fuzz: elapsed: 9s, execs: …
```

feat: Fuzzing test on Base64 encoding and decoding

---

structure/segmenttree/segmenttree.go
structure/segmenttree/segmenttree_test.go

Lazy node value should be accumulated during propagation, because an interval can be updated multiple times.

Fix: segmenttree algorithm bug

---

structure/segmenttree/segmenttree_test.go

Linter tests are failing as the `segmenttree_test.go` (#497) file was not properly formatted. Fixed.

segmenttree: format test file with `gofmt`

---

dynamic/abbreviation.go
dynamic/abbreviation_test.go

Source: [Hackerrank](https://www.hackerrank.com/challenges/abbr/problem)
- [Abbreviation Problem](#abbreviation-problem)
- [Table of Contents](#table-of-contents)
- [Source Code](#source-code)
- [Graphs](#graphs)
- [Flowchart](#flowchart)
- [Control Flow Graph](#control-flow-graph)
- [Data Flow Graph](#data-flow-graph)
- [All-DU-Paths coverage testcases](#all-du-paths-coverage-testcases)
- [MCC coverage testcases](#mcc-coverage-testcases)
- [Other testcases](#other-testcases)
| Path | a | b | Expected | Actual | Verdict |
|---|---|---|---|---|---|
| 1-> 2-6 -> 8 -> 21 | "" | "" | true | true | Pass |
| 1-> 2-6 -> 8 -> 9 -> 10 -> 11 -> 14 -> 15 ... | "a" | "" | true | true | Pass |
| 1-> 2-6 -> 8 -> 9 -> 10 -> 11 -> 14 -> 15 ... | "a" | "b" | false | false | Pass |
| 1-> 2-6 -> 8 -> 9 -> …

add abbreviation problem in dynamic

---

README.md
graph/lowestcommonancestor.go
graph/lowestcommonancestor_test.go

Hi guys! I want to add an implementation of LCA algorihm.

feat: Lowest Common Ancestor (LCA) algorithm.

---

.golangci.yml
go.mod
graph/articulationpoints.go
graph/floydwarshall_test.go
math/binary/checkisnumberpoweroftwo.go
math/pythagoras/pythagoras.go
math/pythagoras/pythagoras_test.go
other/nested/nestedbrackets.go
search/binary.go
search/interpolation.go
structure/segmenttree/segmenttree.go
structure/segmenttree/segmenttree_test.go
structure/stack/stacklinkedlistwithlist.go

This was done automatically with `go1.19 fmt ./...` to see whether the golangci-lint tool is compatible with the gofmt changes.

bump: go 1.19 and fix: fmt issues

---

math/liouville.go
math/liouville_test.go

This PR contains commits related to the implementation of [Liouville lambda function](https://en.wikipedia.org/wiki/Liouville_function). Kindly have a look.

algorithm: Liouville lambda function

---

.golangci.yml
README.md
math/mode.go
sort/patiencesort.go

This re-enables all the golanci-lint linters and checks that are on by default.
Closes #510

feat: re-enable all linters

---

cipher/xor/xor_test.go

Following up from #480, adding fuzzing test to cipher/xor function.
I ran `go test -fuzz=Fuzz -fuzztime 30s cipher/xor/*.go` and got the output below:
```
fuzz: elapsed: 0s, gathering baseline coverage: 0/8 completed
fuzz: elapsed: 0s, gathering baseline coverage: 8/8 completed, now fuzzing with 10 workers
fuzz: elapsed: 3s, execs: 1541453 (513640/sec), new interesting: 0 (total: 8)
fuzz: elapsed: 6s, execs: 3078539 (512364/sec), new interesting: 0 (total: 8)
fuzz: elapsed: 9s, execs: 4648655 (523545/sec), new interesting: 0 (total: 8)
fuzz: elapsed: 12s, execs: 6233252 (528124/sec), new interesting: 0 (total: 8)
fuzz: elapsed: 15s, execs: 7810894 (525865/sec), new interesting: 0 (total: 8)
fuzz: elapsed: 18s, execs: 9394482 (527848/sec), new interesting: 0 (total: 8)
fuzz: elapsed: 21s, …
```

feat: Add fuzzing for cipher/xor

---

math/max/max.go
math/min/min.go
sort/pigeonholesort.go
sort/sorts_test.go

This PR is related to https://github.com/TheAlgorithms/Go/issues/419
Detail:
- use generic for Pigeonhole sort
- use generic for max min Int

feat: Use generic for pigeonholesort and max min Int 

---

cipher/caesar/caesar.go
cipher/caesar/caesar_test.go

feat(cipher/caesar): add fuzzy test to caesar cipher

---

sort/radixsort.go
sort/sorts_test.go

This PR is related to https://github.com/TheAlgorithms/Go/issues/419
Detail:
- use generic for Radix sort Integer
This code is only for Integer. Radix sort can apply for string but we have to re-implement. 
https://www.quora.com/How-can-I-sort-strings-using-Radix-Sort

feat:Use generic for radixsort

---

dynamic/longestcommonsubsequence.go
dynamic/longestcommonsubsequence_test.go

In this PR I remove the _length of the strings_ arguments in `LongestCommonSubsequence`, update the relevant tests and add a test case, which justifies the usage of `utf8.RuneCountInString` instead of `len`.
I think that having the length of the input strings in `LongestCommonSubsequence` is a bit redundant. Also by looking at implementations in other languages like:
- [python](https://github.com/TheAlgorithms/Python/blob/6118b05f0efd1c2839eb8bc4de36723af1fcc364/dynamic_programming/longest_common_subsequence.py#L9),
- [rust](https://github.com/TheAlgorithms/Rust/blob/5bb80cdfbe8092cfaf111f06a8abe9f205849856/src/dynamic_programming/longest_common_subsequence.rs#L5),
- [java](https://github.com/TheAlgorithms/Java/blob/c805437c0c5e057f3ad60c397fe6550eec7be453/src/main/java/com/thealgorithms/d …

refactor: simplity signature of `LongestCommonSubsequence`

---

graph/dijkstra.go
sort/heapsort.go
sort/sorts_test.go

This PR is related to #419 
Details:
- Refactor heapsort to support generic

refactor heapsort to support generic

---

README.md
cipher/polybius/polybius.go
cipher/polybius/polybius_test.go

Hi again, I keep adding fuzz tests for #480, this time for Polybius. I tested it with go test ./cipher/polybius/ to test the corpus and go test -fuzz=FuzzPoly ./cipher/polybius/ to run the fuzzer itself.
If that Is that ok for you to add it let me know. Also if you have any feedbacks about my change let me know so that I can adapt it.
You will see that I did some changes to the errors and restrict some more the possible inputs to the algorithm based a bit on the description of the algorithm in the wikipedia page mentioned at the beginning of the polybius file.
Thanks again for your work!

feat(cipher/polybius): add fuzz test to polybius cipher

---

math/binary/sqrt.go

Fix incorrectly spelled variable name "halfHumber" to "halfNumber".

fix: misspelled variable

---

math/prime/sieve_test.go

I've added a simple benchmark for the prime sieve Generate function, when the input limit is 10.

test: Add benchmark for prime sieve

---

sort/cyclesort.go
sort/sorts_test.go

This adds the cycle sort algorithm. Link for reference: https://en.wikipedia.org/wiki/Cycle_sort

feat: add cycle sort algorithm

---

.github/workflows/ci.yml
.github/workflows/godocmd.yml

This PR updates used `setup-go` action to `v4`.

chore: update `actions/setup-go` to `v4`

---

README.md
structure/set/set.go
structure/set/set_test.go

Modified implementation of set using generics instead of any
Hello, if there is any mistake, please correct me, thanks!

feat: add set implementation using generic

---

strings/genetic/genetic.go

There is a typo in:
https://github.com/TheAlgorithms/Go/blob/30392a3da977d3c3ebb94156489f3bd28d72c89d/strings/genetic/genetic.go#L31
causing some of the CI check [failing](https://github.com/TheAlgorithms/Go/actions/runs/6390761541/job/17344668371?pr=663).

style: use proper spelling

---

strings/horspool/horspool.go
strings/horspool/horspool_test.go

There is some commented out code in [`horspool.go`](https://github.com/TheAlgorithms/Go/blob/58bb31e80f8347c91db049a09d32a4989c06b485/strings/horspool/horspool.go).
This PR _reactivates_ it by making all necessary changes.
When the given pattern is not present in the input string, I used a similar approach to the one in [./search](https://github.com/TheAlgorithms/Go/tree/master/search).
Notes: 
_Reactivates_ [`horspool.go`](https://github.com/TheAlgorithms/Go/blob/58bb31e80f8347c91db049a09d32a4989c06b485/strings/horspool/horspool.go).

feat: reactivate `horspool`

---

graph/bellmanford_test.go

Checking error with == operator might fail on wrapped errors

test: Use error.Is(errorType, errorInstance) to check for error equality

---

sort/cocktailsort.go
sort/sorts_test.go

The cocktail sort (also known as cocktail shaker sort, bidirectional bubble sort, shaker sort, ripple sort, shuffle sort, or shuttle sort) is a variant of the bubble sort algorithm. It extends the bubble sort by operating in both directions (from array's beginning to its end, and from array's end to its beginning).
I based the implementation on the [Wikipedia page about Cocktail Sort](https://en.wikipedia.org/wiki/Cocktail_shaker_sort).
Also added this sort on the `sort_tests.go`

Add Cocktail Sort

---

structure/stack/stack_test.go
structure/stack/stackarray.go
structure/stack/stacklinkedlist.go
structure/stack/stacklinkedlistwithlist.go

- Optimized the push operation by appending to the last element of the array instead of copying the whole array
- Removed the global variable stackArray and created a struct StackArray for it
- Modified stack_test.go file to reflect these changes

optimized stack array implementation 

---

sort/countingsort.go

Counting sort is usually applied to arrays of integers.

fix. Update generics in counting sort

---

sort/binaryinsertionsort.go
sort/sorts_test.go

Binary Insertion sort algorithm implementation in go

feat: add binary insertion sort algorithm

---

README.md
math/fibonacci/fibonacci.go
math/fibonacci/fibonacci_test.go

The calculation of the Fibonacci number is [defined recursively](https://en.wikipedia.org/wiki/Fibonacci_sequence#Definition), but so far there was no recursive implementation yet.
I added the tests, but only run it for numbers up to 10 and I ignored the benchmark purposely, as it would take ages to calculate the 90 Fibonacci number with this approach :)

feat: add recursive fibonacci

---

sort/sorts_test.go
sort/timsort.go

This PR adds simple Timsort sorting algorithm implementation.
Notes: This PR contributes a Timsort sorting algorithm implementation and includes it to the test file.

feat: add Timsort sorting algorithm

---

structure/segmenttree/segmenttree.go

Added comments for the description of NewSegmentTree function

Added description for the NewSegmentTree function

---

.github/workflows/godocmd.yml

Same as TheAlgorithms/Rust#647 - it contains the description of the problem, which this PR solves.

fix: use `GITHUB_ACTOR` in `git config`

---

.github/workflows/upload_coverage_report.yml
.gitignore

This repository [exists on codecov](https://app.codecov.io/gh/TheAlgorithms/Go). Since being able to easily browse through coverage reports it extremely useful, I decided to add a workflow uploading the report there. This PR is similar to TheAlgorithms/Rust#600.

chore: add `upload_coverage_report.yml`

---

graph/kruskal.go

It seems that node initialization in kruskal algorithm, is redundant and it is already being done inside [NewUnionFind](https://github.com/TheAlgorithms/Go/blob/6d839027b6765b7cd14b00ffdd54678bd70dc63e/graph/unionfind.go#L27) function.
This PR aims to fix the twice initialization to get a more clean impl for kruskal algorithm

fix: remove redundant init step for unionFind

---

structure/tree/btree.go
structure/tree/btree_test.go

see https://en.wikipedia.org/wiki/B-tree

feat: Add btree with insertion, deletion, and search

---

README.md
graph/prim.go
graph/prim_test.go

Prim's algorithm is one of the most well known algms for finding minimum spanning tree of a weighted undirected graph, alongside Kruskal's algorithm. I thought it is better to implement it, and repo users can now use both of these algorithms and maybe do any comparison for educational purposes.
to implement the algorithm more efficiently, built-in binary heap in `container/heap` is used as a priority queue.

feat: add prim algorithm to find mst

---

README.md
graph/edmondkarp.go
graph/edmondkarp_test.go

Edmond-Karp's algorithm is an implementation of the Ford-Fulkerson method that uses BFS (Breadth First Search) traversal to find the residual paths between source and sink.
By using BFS, time complexity will be independent from f (max-flow) and max flow can be computed in O(VE<sup>2</sup>)

feat: add edmond-karp algorithm for max-flow

---

README.md
dynamic/traprainwater.go
dynamic/traprainwater_test.go

Provides a function to calculate the amount of trapped rainwater between bars represented by an elevation map using dynamic programming.
- The `TrapRainWater` function calculates the amount of trapped rainwater between the bars represented by the given elevation map.
- It uses dynamic programming to precompute the maximum height of bars to the left and right of each position. Then, it iterates through the array to calculate the amount of trapped rainwater at each position based on the minimum of the left and right maximum heights.
- Finally, it sums up the trapped rainwater for all positions and returns the total amount

Implement Trapped Rain Water algorithm.

---

.github/workflows/upload_coverage_report.yml

Same as TheAlgorithms/Rust#670 - it contains the description of the problem.
~~Before merging, please add the token from https://app.codecov.io/gh/TheAlgorithms/Go/settings as `CODECOV_TOKEN` into the repo secrets.~~ [Token was added](https://github.com/TheAlgorithms/Go/pull/704#pullrequestreview-2012231840).

chore: update `codecov-action` to `v4`

---

README.md
cipher/railfence/railfence.go
cipher/railfence/railfence_test.go

Added rail fence cipher functionality inform of encrypt and decrypt functions to cipher package.

Add railfence cipher

---

.github/workflows/ci.yml
.github/workflows/godocmd.yml
.github/workflows/upload_coverage_report.yml

This PR updates the `actions/setup-go` to `v5`. This helps to avoid the _Node.js 16_ warning.

chore: update `actions/setup-go` to `v5`

---

README.md
math/permutation/next_permutation.go
math/permutation/next_permutation_test.go

A practice to find lexicographically next greater permutation of the given array of integers.
- If there does not exist any greater permutation, then print the lexicographically smallest permutation of the given array.
- The implementation below, finds the next permutation in linear time and constant memory and returns in place.

feat: add next permutation problem

---

dynamic/uniquepaths.go
dynamic/uniquepaths_test.go

Provides a solution to the "Unique Paths" problem. That is, in how many ways can you traverse an m x n matrix from (0, 0) to (m-1, n-1)

feat(uniquepaths): add solution for unique paths problem

---

math/prime/sieve2.go
math/prime/sieve2_test.go

This is a reimplementation for the algorithm sieve of erathosthenes, this reimplementation doesn't use channels and has a better performance than the actual sieve in the repository.
Benchmarks for `limit=10000`
Current implementation:
```
goos: linux                                                                                                                                                                                                  
goarch: amd64
pkg: github.com/TheAlgorithms/Go/math/prime
cpu: AMD Ryzen 5 5600G with Radeon Graphics
BenchmarkSieve10-12            1        3019938961 ns/op         7515624 B/op      40073 allocs/op
PASS
ok      github.com/TheAlgorithms/Go/math/prime  3.206s
```
My implementation:
```
goos: linux …
```

[Reimplementation] Sieve of eratosthenes

---

compression/rlecoding.go
compression/rlecoding_test.go

This PR adds the RLE Compressor.

[IMPLEMENTATION] Compressor RLE

---

structure/hashmap/hashmap.go
structure/hashmap/hashmap_test.go

As I was going through the current implementation of HashMap in Go, I noticed that the following improvements could be made:
**Enhanced Collision Handling:**
- Modified the Put method to handle collisions using linked lists (chaining).
- Ensured that new key-value pairs are correctly inserted even when collisions occur.
**Resizing Logic**
- Refactored the resize method to correctly rehash and relocate all nodes.
- The hash map now doubles its capacity when the load factor exceeds 0.75, ensuring efficient operations.
**Refactored Node Retrieval:**
- Implemented getNodeByKey to traverse the linked list at a given hash index to find the node with the matching key.
- Updated the Get method to use getNodeByKey for retrieving values.
**Code Cleanup:**
- Removed redundant functions (newNode and …

Improved HashMap implementation

---

structure/circularqueue/circularqueue_test.go
structure/circularqueue/circularqueuearray.go

Add implementation of circular queue using array

feat: add circular queue array data structure

---

math/matrix/determinant.go
math/matrix/determinant_test.go

Added the `Determinant` method for the `Matrix` struct under [math/matrix](https://github.com/TheAlgorithms/Go/tree/master/math/matrix).
This method returns the determinant of the matrix.

feat: add determinant implementation for matrix

---

graph/kahn.go
graph/kahn_test.go

Currently, there is only a DFS implementation for topological sort. Therefore, I'm adding Kahn's algorithm.
`graph/kahn.go`: an implementation of the Kahn's algorithm for topological sort, complemented with detailed comments. My code conforms to the `Graph` struct defined in `graph/graph.go`.
`graph/kahn_test.go`: 11 test cases.
1. I suggest renaming `graph/topological.go` to something else to indicate its DFS implementation.
2. `graph/topological_test.go` has a package-level variable called `testCases`. I think it's better to move it into the test function.

feat: add Kahn's algorithm for topological sort

---

graph/kruskal.go
graph/unionfind.go
graph/unionfind_test.go

The current implementation of the union find data structure claims its amortized time complexity is $O(\alpha(n))$, which is incorrect because its `Find` method has no optimization. I added path compression as the necessary optimization. Path splitting and path halving are also valid optimizations, but I think path compression is the most common one.
I changed union-by-size to union-by-rank, which complements path compression effectively.
In addition, I changed the receivers of `Find` and `Union` to pointers. Along with this, I removed the unnecessary return value in `Union`.
I fixed a small typo in the algorithm description and used more consistent variable names.
`graph/kruskal.go` uses `UnionFind`, so I also modified that file to conform to the updated `Union` method.

fix: added path compression to UnionFind

---

dynamic/subsetsum_test.go
math/matrix/matrix_test.go
math/matrix/strassenmatrixmultiply_test.go

As the title says, this PR is for those test that aren't compliant with the lint in the pipeline. Hope this can help to others PR's :)

[Enhancement] Fix failing tests for lint pipeline

---

cipher/dsa/dsa.go
cipher/dsa/dsa_test.go

Hi team, this is my [DSA](https://en.wikipedia.org/wiki/Digital_Signature_Algorithm) implementation. This PR needs a little bit of context.
I tried to follow the exact same algorithm steps as Wikipedia says but this has a big problem: **efficiency**. I'm talking about waiting around 1.5 mins to get the keys generated. Even this is not the exact amount of time because having randomness adds inconsistency (this is the keygen took 10s or 10m but on average 1.5m).
This is why I took a look at the [current go dsa implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/crypto/dsa/dsa.go). As you might see, we have the same aproach in the generation parameters loop (i.e. GPLoop for me, GeneratePrimes for DSA Go implementation), this is so far the most optimal way I found to …

[IMPLEMENTATION] DSA algorithm implementation

---

strings/hamming/hammingdistance.go
strings/hamming/hammingdistance_test.go

This pull request adds an implementation for the `Hamming distance` algorithm under `./strings/hamming` and adds its test to the `hammingdistance_test.go` file.

feat: add string hamming distance algorithm

---

conversion/hexadecimaltobinary.go
conversion/hexadecimaltobinary_test.go
conversion/hexadecimaltodecimal.go
conversion/hexadecimaltodecimal_test.go

Added main and test files for converting hexadecimal to binary and hexadecimal to decimal

Added main and test files for converting hexadecimal to binary and hexadecimal to decimal

---

sort/sorts_test.go
sort/stooge_sort.go

add stooge sort implementation

---

dynamic/burstballoons.go
dynamic/burstballoons_test.go
dynamic/dicethrow.go
dynamic/dicethrow_test.go
dynamic/eggdropping.go
dynamic/eggdropping_test.go
dynamic/interleavingstrings.go
dynamic/interleavingstrings_test.go
dynamic/longestarithmeticsubsequence.go
dynamic/longestarithmeticsubsequence_test.go
dynamic/longestpalindromicsubstring.go
dynamic/longestpalindromicsubstring_test.go
dynamic/maxsubarraysum.go
dynamic/maxsubarraysum_test.go
dynamic/optimalbst.go
dynamic/optimalbst_test.go
dynamic/partitionproblem.go
dynamic/partitionproblem_test.go
dynamic/tilingproblem.go
dynamic/tilingproblem_test.go
dynamic/wildcardmatching.go
dynamic/wildcardmatching_test.go
dynamic/wordbreak.go
dynamic/wordbreak_test.go

This PR adds dynamic programming algorithms essential for competitive programming, interview preparation, and real world applications.
The following algorithms have been added:
Partition Problem
Maximum Subarray Sum (Kadane's Algorithm)
Longest Palindromic Substring
Word Break Problem
Egg Dropping Problem
Tiling Problems
Dice Throw Problem
Burst Balloons
Wildcard Matching
Interleaving Strings
Optimal Binary Search Tree
Longest Arithmetic Subsequence
Changes:
Added implementations for each of the above algorithms using dynamic programming.
Developed corresponding test cases to validate the functionality of the algorithms.
This PR fixes #775

Add Dynamic Programming Algorithms
